export const testIds = {
  appShell: "app-shell",
  topBar: "top-bar",
  leftRail: "left-rail",
  rightInspector: "right-inspector",
  bottomPanel: "bottom-panel",
  timelineCanvas: "timeline-canvas",
  pianoRollCanvas: "piano-roll-canvas",
  agentPanel: "agent-panel",
  inspector: "inspector",
  transport: "transport",
  transportPlay: "transport-play",
  transportStop: "transport-stop",
  transportPosition: "transport-position",
  agentPrompt: "agent-prompt",
  agentSend: "agent-send",
  agentStop: "agent-stop",
  agentThoughtLog: "agent-thought-log",
  agentProposalCard: "agent-proposal-card",
  patchApply: "patch-apply",
  patchReject: "patch-reject",
  exportMidi: "export-midi",
  editorTabs: "editor-tabs",
  jobQueue: "job-queue",
} as const;
