"""Music IR Pydantic models and helpers (mirrors TS Music IR Zod schemas)."""

from cc_music.music.ir import (
    # Leaf models
    Actor,
    BarRange,
    EditCommand,
    EditCommandType,
    IrPatchProposal,
    JsonPatchOp,
    LockState,
    MidiClip,
    Motif,
    MotifSource,
    MusicalDiff,
    MusicIr,
    Note,
    ProjectEvent,
    ProjectEventType,
    ProjectManifest,
    Section,
    Selection,
    Style,
    Track,
    # Helpers
    ir_from_json,
    ir_to_json,
    validate_music_ir,
    validate_patch_proposal,
)

__all__ = [
    "Actor",
    "BarRange",
    "EditCommand",
    "EditCommandType",
    "IrPatchProposal",
    "JsonPatchOp",
    "LockState",
    "MidiClip",
    "Motif",
    "MotifSource",
    "MusicalDiff",
    "MusicIr",
    "Note",
    "ProjectEvent",
    "ProjectEventType",
    "ProjectManifest",
    "Section",
    "Selection",
    "Style",
    "Track",
    "ir_from_json",
    "ir_to_json",
    "validate_music_ir",
    "validate_patch_proposal",
]
